; timining-critical flipping of top border colours
; 224 t-states per row
TOP_BORDER_RENDER:		
	LD		C, $FE
	LD 		HL, TOP_BORDER_BUFFER

	LD 		B, 56		; 56 top border without contention
TOP_BORDER_RENDER_LOOP:	
	;11 cols
	LD 		A, B

	OUTI	
	OUTI	
	OUTI	
	OUTI	

	OUTI	
	OUTI	
	OUTI	
	OUTI	

	OUTI	
	OUTI	
	OUTI	

	; hblank & timing desu...
	.5 NOP
	LD  	B, A
	LD 		A, (HL)

	DJNZ    TOP_BORDER_RENDER_LOOP

	LD  	A, 0		; black border
	OUT		($FE), A

	RET								; TOP_BORDER_RENDER

; 56 x 11
TOP_BORDER_BUFFER:
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLK

	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLU
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

	DEFB 	0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK
	DEFS 	11, COL_BLK

